FROM alpine:latest

RUN apk update && apk add --no-cache build-base git

RUN git clone https://github.com/catseye/Befunge-93.git && \
    cd Befunge-93 && \
    make && \
    cp bin/bef /usr/bin

COPY . /app
WORKDIR /app

CMD ["bef", "./app/main.bf"]