FROM gcc:13.2 as builder

ONBUILD COPY . /app
WORKDIR /app

ONBUILD RUN make

FROM alpine:latest as runner

RUN apk add libc6-compat

ONBUILD WORKDIR /app
ONBUILD COPY --from=builder ./compiled-app ./compiled-app

ONBUILD CMD ["./compiled-app"]
